apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos-monkey
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaos-monkey
  namespace: workloads
subjects:
  - kind: ServiceAccount
    name: chaos-monkey
    namespace: chaos-monkey
roleRef:
  kind: ClusterRole
  name: chaos-monkey
  apiGroup: rbac.authorization.k8s.io
